### ISSUE TITLE
Heading Bold, Adding Anchors , Underline , Italic Functions is not working 

### ISSUE THREAD

**Issue by dazunE** [iseulde/editor-blocks#1]
In the headings when we highlight it we can see the tooltip for the Bold, Italic, Underline and hyperlinking etc, none of this functions is working  
![screen shot 2017-02-10 at 9 57 09 am](https://cloud.githubusercontent.com/assets/4003531/22814220/b7b4724a-ef77-11e6-8d4f-79b034667781.png)

**Comment by dazunE** [comment]
Same issue has inside the paragraph as well

**Comment by iseulde** [comment]
Hi! I don't think this happens in this repo: https://iseulde.github.io/editor-blocks/

Maybe you're looking for https://github.com/wordpress/gutenberg?
