### ISSUE TITLE
Oddities in clicking behaviour

### ISSUE THREAD

**Issue by karmatosed** [iseulde/editor-blocks#3]
![editor-clicking](https://cloud.githubusercontent.com/assets/253067/22971659/5728d89e-f36e-11e6-9ae9-250fc4baa6b3.gif)

@mapk reported this here: https://make.wordpress.org/design/2017/02/09/initial-editor-blocks-prototype-editor-testing/#comment-25093

> Found some clicking oddities with the inline style editing of the entire block, after clicking _bold_ and then _bold_ again, it got switched to a layout inline editor abruptly. Example gif below.

**Comment by iseulde** [comment]
This should be fixed.

**Comment by iseulde** [comment]
I think this should be fixed?

**Comment by mapk** [comment]
Works for me now, thanks!

**Comment by iseulde** [comment]
🎉
