### ISSUE TITLE
Add block button not dismissed

### ISSUE THREAD

**Issue by karmatosed** [iseulde/editor-blocks#4]
Reported on testing thread:

> If I press the add block button while the text alignment is visible the latter is not dismissed and stays on top:

https://cloudup.com/cmA_eZKdExg

https://make.wordpress.org/design/2017/02/09/initial-editor-blocks-prototype-editor-testing/#comment-25097

**Comment by iseulde** [comment]
Looks like the other repo :)
Please report at https://github.com/WordPress/gutenberg/issues
