### ISSUE TITLE
X button could be interpreted as delete

### ISSUE THREAD

**Issue by karmatosed** [iseulde/editor-blocks#6]
From prototype testing:

> The [x] button to clear the formatting of a bock and revert it back to a paragraph could easily be interpreted as deleting the block instead. Attempting to use it once will disillusion you, but seeing that symbol in a location like that is so psychologically ingrained that my brain still thinks it is for deleting the block for a split-second.

https://make.wordpress.org/design/2017/02/09/initial-editor-blocks-prototype-editor-testing/#comment-25105

**Comment by iseulde** [comment]
Fixed, more or less!
